export interface TeamMember {
  id: string;
  firstName: string;
  lastName: string;
  /** Display label under the carousel thumbnail */
  displayName: string;
  role: string;
  email: string;
  bio: string;
  imageSrc: string;
  shortName: string;
}

export const SECTION_QUOTE =
  '"Our Collective Expertise, Driven by Passion and a Commitment to Excellence"';

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "1",
    firstName: "Tshering",
    lastName: "Dorji",
    displayName: "Tshering Dorji",
    shortName: "T. Dorji",
    role: "CEO/Urban Designer/Architect",
    email: "cringdorji@gmail.com",
    bio: "Prior to founding the Architectural and Planning firm Tshering Dorji served in the Bhutan Civil service for 15 years with his final appointment being Chief Urban Planner in Ministry of Infrastructure and Transport.  He now leads the firm across urban planning, architecture, and design-build projects.",
    imageSrc: "/image/profile/tshering_dorji.png",
  },
  {
    id: "2",
    firstName: "Dhendup",
    lastName: "Dorji",
    displayName: "Dhendup Dorji",
    shortName: "D. Dorji",
    role: "Sr. Architect",
    email: "dhendupdorji350@gmail.com",
    bio: "Prior to working in Consult2T, Dhendup Dorji served as a Healthcare Architect in the Ministry of Health for 2 years. He now manages company documentation and oversees the execution of all architectural projects.",
    imageSrc: "/image/profile/dendup_dorji.png",
  },
  {
    id: "3",
    firstName: "Kinley",
    lastName: "Dorji",
    displayName: "Kinley Dorji",
    shortName: "K. Dorji",
    role: "Architect",
    email: "kinleydorji0313@gmail.com",
    bio: "Kinley Dorji is an architect with experience across diverse architectural projects, responsible for construction oversight, with a strong focus on quality assurance and the accurate translation of design drawings into built form.",
    imageSrc: "/image/profile/kinley_dorji.png",
  },
  {
    id: "4",
    firstName: "Kinley",
    lastName: "Seldon",
    displayName: "Kinley Sonam Seldon",
    shortName: "K.S. Seldon",
    role: "Architect",
    email: "kinleysonamseldon@gmail.com",
    bio: "Kinley Sonam Seldon is an architect actively engaged in urban planning and design, contributing to a wide range of planning and urban design projects while effectively integrating architectural solutions alongside",
    imageSrc: "/image/profile/kinley_sonam_seldon.png",
  },
  {
    id: "5",
    firstName: "Kinzang",
    lastName: "Wangmo",
    displayName: "Kinzang Tshoki Wangmo",
    shortName: "K.T. Wangmo",
    role: "Architect",
    email: "kinzangtw@gmail.com",
    bio: "Kinzang Tshoki Wangmo is an architect whose work spans diverse architectural projects, alongside urban planning and urban design. She is involved in design development, planning, project management, and site execution across a range of projects.",
    imageSrc: "/image/profile/kinzang_tshokey_wangmo.png",
  },
  {
    id: "6",
    firstName: "Ugyen",
    lastName: "Chogyel",
    displayName: "Ugyen Chogyel",
    shortName: "U. Chogyel",
    role: "Architect",
    email: "uchogyel@gmail.com",
    bio: "Ugyen Chogyel is an architect who supports a range of architectural works, contributing to design development and assisting in the execution of projects across different stages",
    imageSrc: "/image/profile/ugyen_chogyal.png",
  },
  {
    id: "7",
    firstName: "Abhinay",
    lastName: "Rao",
    displayName: "Abhinay Rao",
    shortName: "A. Rao",
    role: "Sr. Urban Planner/Designer",
    email: "Abhinayrao12@gmail.com",
    bio: "Abhinay is an Urban Designer and Planner with 11+ years of international experience leading master plans, smart city frameworks, and local area plans across Bhutan, India, Australia, the US, and the UK. He combines core urban design principles with GIS spatial analytics to transform complex planning challenges into sustainable, actionable urban environments",
    imageSrc: "/image/profile/abhinay_rao.png",
  },
  {
    id: "8",
    firstName: "Rabsel",
    lastName: "Wangchuk",
    displayName: "Rabsel Wangchuk",
    shortName: "R. Wangchuk",
    role: "Electrical Engineer",
    email: "wangchukrabsel1@gmail.com",
    bio: "Rabsel Wangchuk is an electrical engineer who supports a range of electrical engineering works, contributing to internal electrical design and drawings, lighting layouts, and coordination of electrical systems within building designs.",
    imageSrc: "/image/profile/rabsel_wangchuk.png",
  },
  {
    id: "9",
    firstName: "Sangay",
    lastName: "Tshering",
    displayName: "Sangay Tshering",
    shortName: "S. Tshering",
    role: "Civil Engineer",
    email: "sangaytsheringst02@gmail.com",
    bio: "Sangay Tshering is an aspiring structural engineer with a growing focus on structural analysis, seismic design, and building design, developing practical solutions that contribute to safe and resilient structures.",
    imageSrc: "/image/profile/sangay_tshering.png",
  },

  {
    id: "10",
    firstName: "Sonam",
    lastName: "Lhamo",
    displayName: "Sonam Yangchen Lhamo",
    shortName: "S.Y Lhamo",
    role: "Architect",
    email: "sonamylhamo04@gmail.com",
    bio: "Sonam Yangchen Lhamo is an architect who contributes to design development and supports the preparation and development of architectural projects across different stages.",
    imageSrc: "/image/profile/sonam_yangchen_lhamo.png",
  },
  {
    id: "11",
    firstName: "Tandin",
    lastName: "Pem",
    displayName: "Tandin Pem",
    shortName: "T. Pem",
    role: "Accounts Officer",
    email: "pemtandin24@gmail.com",
    bio: "Tandin Pem oversees company bookkeeping, financial reporting, and daily accounting operations. With a background in business studies and financial management, she  ensures accurate, efficient, and transparent financial workflows for the organization",
    imageSrc: "/image/profile/tandin_pem.png",
  },
  {
    id: "12",
    firstName: "Tshering",
    lastName: "Choki",
    displayName: "Tshering Choki",
    shortName: "T. Choki",
    role: "Architect",
    email: "cringchox02@gmail.com",
    bio: "Tshering Choki is an architect who supports architectural design and project development, contributing to various stages of the design process.",
    imageSrc: "/image/profile/tshering_choki.png",
  },
  {
    id: "13",
    firstName: "Pema",
    lastName: "Tshering",
    displayName: "Pema Tshering",
    shortName: "P. Tshering",
    role: "Site Manager",
    email: "pemat094@gmail.com",
    bio: "Pema Tshering is a Site Manager responsible for on-site management, overseeing day-to-day operations while maintaining accurate financial records across project sites.",
    imageSrc: "/image/profile/pema_tshering.png",
  },
  // {
  //   id: "14",
  //   firstName: "Tenzin",
  //   lastName: "Yoezer",
  //   displayName: "Tenzin Choyeng Yoezer",
  //   shortName: "T.C. Yoezer",
  //   role: "Accounts and Administration Officer",
  //   email: "tenzinyoezer799@gmail.com",
  //   bio: "Tenzin oversees the firm’s financial and administrative functions, managing accounts, maintaining records, and ensuring smooth day-to-day office operations.",
  //   imageSrc: "/image/profile/tenzin_choyeng_yoezer.png",
  // },

  {
    id: "15",
    firstName: "Dorji",
    lastName: "Tshering",
    displayName: "Dorji Tshering",
    shortName: "D. Tshering",
    role: "Transport Engineer/Advisor",
    email: "dorjitsherings@gmail.com",
    bio: "Dorji Tshering is a Transport Engineer and former Minister of the Ministry of Works and Human Settlement, bringing over 12 years of experience as a Road Engineer in the same ministry. As an advisor to the firm, he offers deep expertise in transportation engineering and geotechnical aspects, providing strategic guidance across infrastructure and planning projects.",
    imageSrc: "/image/profile/dorji_tshering.png",
  },

  {
    id: "16",
    firstName: "Kinzang",
    lastName: "Deki",
    displayName: "Kinzang Deki",
    shortName: "K. Deki",
    role: "Urban Planner/Advisor",
    email: "deki20508@gmail.com",
    bio: "Kinzang Deki is an Urban Planning Specialist and advisor to the firm, bringing extensive experience from her tenure at the Ministry of Works and Human Settlement, where she served as a Senior Urban Planner until 2025. She provides strategic guidance on planning projects, drawing on her deep expertise in urban development and policy.",
    imageSrc: "/image/profile/kinzang_deki.png",
  },
  {
    id: "17",
    firstName: "Dechen",
    lastName: "Norbu",
    displayName: "Dechen Norbu",
    shortName: "D. Norbu",
    role: "Civil Engineer/Advisor",
    email: "dechennorbhu@gmail.com",
    bio: "Dechen Norbu is an advisor to the firm with a strong background in civil engineering, construction management, and procurement. Drawing on 17 years of experience at the Ministry of Works and Human Settlement, where he served as Chief Engineer, he contributes valuable insight to the delivery and management of complex projects",
    imageSrc: "/image/profile/dechen_norbu.png",
  },
  {
    id: "18",
    firstName: "Singay",
    lastName: "Dorji",
    displayName: "Singay Dorji",
    shortName: "S. Dorji",
    role: "Electrical Engineer/Advisor",
    email: "singay.dozy@gmail.com",
    bio: "Singay Dorji is an Electrical Engineer and advisor to the firm, bringing extensive experience from working with diverse clients. His expertise in HVAC systems and building services adds valuable technical insight to the design and execution of projects.",
    imageSrc: "/image/profile/singey_dorji.png",
  },
];
